//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaModelos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int id_detalle { get; set; }
        public int id_cFactura { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        
        public virtual CAB_FACTURA CAB_FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
