//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaModelos.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliveryEntidades1 : DbContext
    {
        public DeliveryEntidades1()
            : base("name=DeliveryEntidades1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAB_FACTURA> CAB_FACTURA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual DbSet<ESTADO_ENVIO> ESTADO_ENVIO { get; set; }
        public virtual DbSet<ESTADO_PAGO> ESTADO_PAGO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO_CATEGORIA> PRODUCTO_CATEGORIA { get; set; }
        public virtual DbSet<LOG_IN> LOG_IN { get; set; }
    
        public virtual int rptCantidadProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptCantidadProductos");
        }
    
        public virtual int rptCantidadProductos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptCantidadProductos1");
        }
    
        public virtual ObjectResult<rptCantidadProductos11_Result> rptCantidadProductos11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCantidadProductos11_Result>("rptCantidadProductos11");
        }
    
        public virtual ObjectResult<rptMontoAgrupadoxCliente_Result> rptMontoAgrupadoxCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptMontoAgrupadoxCliente_Result>("rptMontoAgrupadoxCliente");
        }
    
        public virtual ObjectResult<rptVentasCategoriaxMes_Result> rptVentasCategoriaxMes(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptVentasCategoriaxMes_Result>("rptVentasCategoriaxMes", fechaInicioParameter, fechaFinParameter);
        }
    }
}
